USE [master]
RESTORE DATABASE [DB NAME HERE] FROM  DISK = N'C:\SQLScripts\Backup\DBNAMEHERE.bak' WITH  FILE = 1,  MOVE N'DBNAMEHERE' TO N'G:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data\DBNAMEHERE.mdf',  MOVE N'DBNAMEHERE_log' TO N'H:\Program Files\Microsoft SQL Server\MSSQL13.MSSQLSERVER\MSSQL\Data\DBNAMEHERE_log.ldf',  NOUNLOAD,  REPLACE,  STATS = 5

GO

